# Generated by Django 4.0.5 on 2022-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCatagory',
            new_name='PostCategory',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='blogimg'),
        ),
    ]
